### ISSUE TITLE
Not show correct recent visited directories. Recent visited directories not in chronological way.

### ISSUE THREAD

**Issue by alexei-28** [vifon/dired-recent.el#3]
```
Linux Mint 20
Emacs 27
dired, dired-recent
```

Steps:

```
1. "recentf-mode" is turn on
2. Go to directory "Download". Use "Jump to bookmark" (C-x r b). Input "Download"
3. As result in Dired mode open folder "/home/alexeij/Downloads/"
4. Go to directory "Temp". Use "Jump to bookmark" (C-x r b).  Input "Temp"
5. As result in Dired mode open folder "/home/alexeij/Temp/"
6. Go to directory "dev". Use  "Jump to bookmark" (C-x r b).  Input "dev"
7. As result in Dired mode open folder "/home/alexeij/dev/"
```
Nice. Now I want to see history of recent visited directories in chronological way.

So I use:

`dired-recent-open`
But in minibuffer show another directories.

Why?

**Comment by vifon** [comment]
Do you have `dired-recent-mode` enabled?

**Comment by alexei-28** [comment]
> Do you have `dired-recent-mode` enabled?

Yes, 
`
 '(dired-recent-mode t nil (dired-recent))`

As you can see the result is NOT in chronological way.

![1](https://user-images.githubusercontent.com/303539/135758961-29faa6c6-9e92-4225-91e5-13d7f730ccb7.png)

P.S. I think the result must like this:
```

dev/
Temp/
Download/
...
```

**Comment by vifon** [comment]
What do you use for these completions? Ivy? Selectrum?

**Comment by alexei-28** [comment]
> What do you use for these completions? Ivy? Selectrum?

I use Selectrum

**Comment by vifon** [comment]
Do you use it with Prescient? If so, it is responsible for "smart" sorting of the candidates list. I'm not sure who is canonically responsible of adding the exception to it: me, them or the user (you). I'd say using it locally in your config for now would be the safest bet. If you'll find the exact expression to do it, I can see if it's viable to add it on my side (without adding a hard dependency on Prescient).

**Comment by vifon** [comment]
From the Selectrum docs:

> The option `selectrum-should-sort` controls whether preprocessing functions should sort.

**Comment by vifon** [comment]
OK, I see how other packages do that. I'll add it tonight. Thanks for suggesting it, even if indirectly!

**Comment by vifon** [comment]
Please confirm it works now.

**Comment by alexei-28** [comment]
`  dired-recent       20211004.1924 `

It's better, but not ideal. What I mean?
My folder tree is:

```
Temp\MyProject
- subfolder1\src
- subfolder2\target
```

Steps (on dired mode)
1. Go to folder `Temp`
2. Press RET (open folder `MyProject`)
3. Open folder `subfolder1`
4. Open folder `subfolder2`


here result (`dired-recent-open`):
![1](https://user-images.githubusercontent.com/303539/135972651-acc3700e-7b44-4571-bcc2-e8402ca2c918.png)
Nice. It's correct.

Then I do the next steps (in dired mode):
1. Open folder `subfolder1\src`
2. Open folder `subfolder2\target`

And here result:
![2](https://user-images.githubusercontent.com/303539/135972785-221438e2-1ae3-4520-9414-c60274ef48fb.png)

Nice. It's also correct.

And last steps (in dired mode):
1. Again open folder `subfolder1`
2. Again open folder `subfolder2`

And here result 
![3](https://user-images.githubusercontent.com/303539/135972898-4a94cd7e-ab81-4769-829c-f1d686a8e869.png)
As you can see nothing change. 
I think the result must be like this:
```
~/Temp/myProject/subfolder1/
~/Temp/myProject/subfolder2/
~/Temp/myProject/subfolder2/target
~/Temp/myProject/subfolder1/src
```

**Comment by vifon** [comment]
Do you kill the `subfolder1` and `subfolder2` buffers in between? That's probably it. The list is updated only when `dired-mode` is enabled, so usually when the new `dired` buffer gets created. It's indeed something to look into, but it's a separate issue requiring more heavy-duty hooks than just hooking into `dired-mode-hook`.

**Comment by alexei-28** [comment]
> Do you kill the `subfolder1` and `subfolder2` buffers in between? That's probably it. The list is updated only when `dired-mode` is enabled, so usually when the new `dired` buffer gets created. It's indeed something to look into, but it's a separate issue requiring more heavy-duty hooks than just hooking into `dired-mode-hook`.

No, I'm not kill any buffers.
Here dired-recent

![1](https://user-images.githubusercontent.com/303539/136254020-bac1cd91-122f-4c94-9e2f-62dafa622399.png)
And here list of all buffers
![2](https://user-images.githubusercontent.com/303539/136254058-03c6e346-3020-4d14-a255-c74486ea3934.png)
